package dqgg;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.*;
/**
 * Formulário de Quiremas.
 * @author AntonioSousa
 */
public class FormQuirema extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    JFileChooser fcImagem;   // Janela (dialog) para selecao de arquivos de imagem    
    BD dqggDB;
    Quirema quirAtual = new Quirema();   // Registro atualmente exibido
    HashMap filtroConsulta = new HashMap();        // Filtro de consulta atual
    ArrayList<Quirema> quirsConsulta = new ArrayList<Quirema>();        // registros retornado pela consulta corrente
    ArrayList<Categoria> categorias;
    int indiceConsulta = 0;
    
    enum Modo {INCLUSAO, ALTERACAO, CONSULTA};
    Modo modoForm = Modo.ALTERACAO;
    
    /**
     * Creates new form FormBD
     */
    public FormQuirema() {
        initComponents();        
                                
        quirAtual = quirAtual.buscaPrimeiro();                
        categorias = this.quirAtual.getCategoria().buscaTodos();
        
        for (Categoria c: categorias)
            this.comboCategoria.addItem(c.getDescricao());
                
        quirAtual = quirAtual.buscaPrimeiro();
        if (quirAtual != null)
            this.atualizaFormulario(quirAtual);
        else
            this.entraModoInclusao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelNavigator = new javax.swing.JPanel();
        btPrimeiro = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        btUltimo = new javax.swing.JButton();
        btIncluir = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        txtAbreviatura = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtLinha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtColuna = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setTitle("DQSG(G) - Sematosemas");
        setMaximumSize(new java.awt.Dimension(855, 310));
        setMinimumSize(new java.awt.Dimension(855, 310));
        setPreferredSize(new java.awt.Dimension(855, 310));

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Categoria:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Abreviatura:");

        PanelNavigator.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btPrimeiro.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btPrimeiro.setText("|<");
        btPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrimeiroActionPerformed(evt);
            }
        });

        btAnterior.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btAnterior.setText("<");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btProximo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btProximo.setText(">");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        btUltimo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btUltimo.setText(">|");
        btUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUltimoActionPerformed(evt);
            }
        });

        btIncluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btConfirmar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btConsultar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNavigatorLayout = new javax.swing.GroupLayout(PanelNavigator);
        PanelNavigator.setLayout(PanelNavigatorLayout);
        PanelNavigatorLayout.setHorizontalGroup(
            PanelNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavigatorLayout.createSequentialGroup()
                .addComponent(btPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConfirmar)
                .addGap(4, 4, 4)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelNavigatorLayout.setVerticalGroup(
            PanelNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavigatorLayout.createSequentialGroup()
                .addGroup(PanelNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        txtAbreviatura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("Posição de Exibição");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("     Linha: ");

        txtLinha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Coluna: ");

        txtColuna.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtColuna, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 347, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtColuna, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Posição de Exibição");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtAbreviatura, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(PanelNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAbreviatura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("Banco de Dados do DQG - SEMATOSEMAS");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void entraModoConsulta()
    {        
        this.modoForm = Modo.CONSULTA;
        this.limpaCampos();
        // Altera a cor dos campos 
        this.txtNome.setBackground(DQGG.corConsulta);
        this.txtAbreviatura.setBackground(DQGG.corConsulta);
        this.comboCategoria.setBackground(DQGG.corConsulta);  
        this.txtLinha.setBackground(DQGG.corConsulta);
        this.txtColuna.setBackground(DQGG.corConsulta);        
    }
    
    private void entraModoAlteracao()
    {
        this.modoForm = Modo.ALTERACAO;
        // Altera a cor dos campos 
        this.txtNome.setBackground(DQGG.corAlteracao);
        this.txtAbreviatura.setBackground(DQGG.corAlteracao);
        this.comboCategoria.setBackground(DQGG.corAlteracao);
        this.txtLinha.setBackground(DQGG.corAlteracao);
        this.txtColuna.setBackground(DQGG.corAlteracao);
    }
    
    private void entraModoInclusao()
    {
        this.modoForm = Modo.INCLUSAO;
        this.limpaCampos();
        // Altera a cor dos campos 
        this.txtNome.setBackground(DQGG.corInsercao);
        this.txtAbreviatura.setBackground(DQGG.corInsercao);
        this.comboCategoria.setBackground(DQGG.corInsercao);
        this.txtLinha.setBackground(DQGG.corInsercao);
        this.txtColuna.setBackground(DQGG.corInsercao);
    }
    
    private void atualizaFormulario(Quirema rep)
    {
        // Atualiza os valores dos campos de texto
        this.txtNome.setText(rep.getDescricao());
        this.txtAbreviatura.setText(rep.getAbreviatura());
        this.comboCategoria.setSelectedItem(this.quirAtual.getCategoria().getDescricao());
        this.txtLinha.setText(String.valueOf(rep.getLinha()));
        this.txtColuna.setText(String.valueOf(rep.getColuna()));       
    }
    
    private void limpaCampos()
    {
        // Atualiza os valores dos campos de texto
        this.txtNome.setText("");
        this.txtAbreviatura.setText("");
        this.comboCategoria.setSelectedIndex(-1);
        this.txtLinha.setText("");
        this.txtColuna.setText("");
    }
    
    /* O botão de confirmação funciona de forma diferente dependendo do modo do formulario */
    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        HashMap camposAlterados = new HashMap(); 
        boolean alteraAbrev = false;    // indica se a operacao de atualizacao ira alterar a abreviatura
                
        if (this.modoForm == Modo.INCLUSAO)
        {
            // Valida os campos 
            if (this.txtNome.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Campo Nome obrigatório!","ERRO",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (this.txtAbreviatura.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Campo Abreviatura obrigatório!","ERRO",JOptionPane.ERROR_MESSAGE);
                return;
            }
         
             Categoria categoria = (Categoria) categorias.get(comboCategoria.getSelectedIndex());             
            
            // Insere a representacao no banco
            Quirema rep = new Quirema(0, this.txtNome.getText(), this.txtAbreviatura.getText(), categoria.getId(), this.txtLinha.getText(), this.txtColuna.getText());            
            rep.insereBD();
            this.entraModoAlteracao();
        
            //Navega para o registro incluido
            Quirema r = this.quirAtual.buscaUltimo();            
            this.atualizaFormulario(quirAtual=r);
            
        } else if (this.modoForm == Modo.CONSULTA) {
            if (this.quirsConsulta.isEmpty())
            {   
                // Verifica os campos que foram preenchidos            
                if (!this.txtNome.getText().isEmpty())           
                    this.filtroConsulta.put("NOME", this.txtNome.getText());

                if (!this.txtAbreviatura.getText().isEmpty())            
                    this.filtroConsulta.put("ABREVIATURA", this.txtAbreviatura.getText());            

                if (this.filtroConsulta.isEmpty()) 
                {
                   JOptionPane.showMessageDialog(this,"Não há parâmetros para busca!","ALERTA",JOptionPane.INFORMATION_MESSAGE);               
                }
                else
                {
                   this.quirsConsulta = this.quirAtual.consultaBD(this.filtroConsulta);    
                   this.quirAtual = this.quirsConsulta.get(0);    // pega o primeiro registro da consulta
                   indiceConsulta = 0;
                   this.atualizaFormulario(quirAtual);
                }
            }
            
        } else if (this.modoForm == Modo.ALTERACAO) {
            // Valida os campos 
            if (this.txtNome.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Campo Nome obrigatório!.","ERRO",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (this.txtAbreviatura.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Campo Abreviatura obrigatório!.","ERRO",JOptionPane.ERROR_MESSAGE);
                return;
            }
      
            // Verifica os campos que foram alterados            
            if (!this.txtNome.getText().equals(this.quirAtual.getDescricao()))           
                camposAlterados.put("NOME", this.txtNome.getText());
            
            if (!this.txtAbreviatura.getText().equals(this.quirAtual.getAbreviatura()))
            {       
                alteraAbrev = true;    
                camposAlterados.put("ABREVIATURA", this.txtAbreviatura.getText());                 
            }            
            
            Categoria categoria = (Categoria) categorias.get(comboCategoria.getSelectedIndex());            
            if (categoria.getId() != this.quirAtual.getCategoria().getId())
            {
                camposAlterados.put("ID_CATEGORIA", categoria.getId());
            }
            
            if (!this.txtLinha.getText().equals(String.valueOf(this.quirAtual.getLinha())))           
                camposAlterados.put("POSLINHA", this.txtLinha.getText());
            
            if (!this.txtColuna.getText().equals(String.valueOf(this.quirAtual.getColuna())))           
                camposAlterados.put("POSCOLUNA", this.txtColuna.getText());
            
            if (camposAlterados.isEmpty()) 
            {
               JOptionPane.showMessageDialog(this,"Não há alterações a serem salvas!.","ALERTA",JOptionPane.INFORMATION_MESSAGE);               
            }
            else
            {                
               if (alteraAbrev)
               {
                    int opcao = JOptionPane.showConfirmDialog(this,
                                                  "Essa operação afetará todos os Aloquiros e Sinais relacionados a este sematosema. Deseja continuar?",
                                                  "CONFIRMAÇÃO",
                                                  JOptionPane.YES_NO_OPTION);
                    if (opcao == JOptionPane.NO_OPTION) // Se o usuário cancelar
                    {
                        alteraAbrev = false;
                        return;
                    }
               } 
                
               if (this.quirAtual.atualizaBD(camposAlterados))                    
               {
                   JOptionPane.showMessageDialog(this,"Dados alterados com sucesso!");
                   this.quirAtual = new Quirema().buscaPorId(this.quirAtual.getId());
                   this.atualizaFormulario(this.quirAtual);
               }
               else
                   JOptionPane.showMessageDialog(this,"Erro durante a atualização de dados!","ERRO",JOptionPane.ERROR_MESSAGE);
            }                       
            alteraAbrev = false;
        }  
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrimeiroActionPerformed
        if (this.modoForm == Modo.ALTERACAO)    // vai para o primeiro registro da tabela
        {
            Quirema r = this.quirAtual.buscaPrimeiro();
            if (r != null)
                this.atualizaFormulario(quirAtual=r);
        }
        else if ((this.modoForm == Modo.CONSULTA)&&(!this.quirsConsulta.isEmpty()))    // vai para o primeiro registro da consulta
        {
            this.quirAtual = this.quirsConsulta.get(0);
            this.atualizaFormulario(quirAtual);
        }
    }//GEN-LAST:event_btPrimeiroActionPerformed

    private void btUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUltimoActionPerformed
        if (this.modoForm == Modo.ALTERACAO)
        {
            Quirema r = this.quirAtual.buscaUltimo();
            if (r != null)
                this.atualizaFormulario(quirAtual=r);
        }
        else if ((this.modoForm == Modo.CONSULTA)&&(!this.quirsConsulta.isEmpty()))    // vai para o ultimo registro da consulta
        {
            indiceConsulta = this.quirsConsulta.size()-1;
            this.quirAtual = this.quirsConsulta.get(indiceConsulta);
            this.atualizaFormulario(quirAtual);
        }
    }//GEN-LAST:event_btUltimoActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        if (this.modoForm == Modo.ALTERACAO)
        {
            Quirema r = this.quirAtual.buscaAnterior(this.quirAtual);
            if (r != null)
                this.atualizaFormulario(quirAtual=r);
        }
        else if ((this.modoForm == Modo.CONSULTA)&&(!this.quirsConsulta.isEmpty()))    // vai para o registro anterior da consulta
        {
            if (indiceConsulta > 0) 
                indiceConsulta--;
            this.quirAtual = this.quirsConsulta.get(indiceConsulta);
            this.atualizaFormulario(quirAtual);
        }
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        if (this.modoForm == Modo.ALTERACAO)
        {
            Quirema r = this.quirAtual.buscaProximo(this.quirAtual);
            if (r != null)
                this.atualizaFormulario(quirAtual=r);
        }
        else if ((this.modoForm == Modo.CONSULTA)&&(!this.quirsConsulta.isEmpty()))    // vai para o registro anterior da consulta
        {
            if (indiceConsulta < (this.quirsConsulta.size()-1)) 
                indiceConsulta++;
            this.quirAtual = this.quirsConsulta.get(indiceConsulta);
            this.atualizaFormulario(quirAtual);
        }
    }//GEN-LAST:event_btProximoActionPerformed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        if (this.modoForm == Modo.CONSULTA)   //Limpa os registros e o filtro de consulta
        {              
                 this.quirsConsulta.clear();           
                 this.filtroConsulta.clear();    
        }        
        this.entraModoInclusao();        
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
           if (this.modoForm == Modo.CONSULTA)   //Limpa os registros e o filtro de consulta
           {              
                    this.quirsConsulta.clear();           
                    this.filtroConsulta.clear();    
           }
            this.entraModoAlteracao();
            if (this.quirAtual == null)  // consulta que não retornou nenhum registro
            {
                this.quirAtual = this.quirAtual.buscaPrimeiro();                
            }
            this.atualizaFormulario(quirAtual);       
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        if (this.modoForm == Modo.CONSULTA)
        {
            //if (!this.quirsConsulta.isEmpty())   // retira o filtro de consulta
                this.quirsConsulta.clear();
                this.filtroConsulta.clear();
            
        }
        this.entraModoConsulta();        
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (this.modoForm != Modo.ALTERACAO)
            return;
        
        int opcao = JOptionPane.showConfirmDialog(this,
                                              "Confirmar exclusão do registro?",
                                              "CONFIRMAÇÃO",
                                              JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) 
        {
           // Pega o registro anterior ao atual
           Quirema rep = this.quirAtual.buscaAnterior(quirAtual);
           if (rep == null)
               rep = this.quirAtual.buscaProximo(quirAtual);
                      
           if (this.quirAtual.exclui()){
               JOptionPane.showMessageDialog(this,"Dados alterados com sucesso!");               
               this.atualizaFormulario(this.quirAtual=rep);
           } else {
               JOptionPane.showMessageDialog(this,"Erro durante a esclusão de dados!","ERRO",JOptionPane.ERROR_MESSAGE);
           }
        }
        
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuirema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuirema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuirema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuirema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuirema().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNavigator;
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btPrimeiro;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btUltimo;
    private javax.swing.JComboBox comboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAbreviatura;
    private javax.swing.JTextField txtColuna;
    private javax.swing.JTextField txtLinha;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
