
package dqgg;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 * Utilizado apenas para auxiliar a encontrar falhas na base de dados
 * Gera uma lista de todos os sinais da base.
 * @author AntonioSousa
 */
public class FormLista extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    /**
     * Creates new form FormLista
     */
    public FormLista(String consultaSQL ) {
        initComponents();
        try {
                ResultSet rs = DQGG.bd.consulta(consultaSQL);

                // get columns info
                ResultSetMetaData rsmd = rs.getMetaData();
                int columnCount = rsmd.getColumnCount();

                // for changing column and row model
                DefaultTableModel tm = (DefaultTableModel) tbCategorias.getModel();

                // clear existing columns 
                tm.setColumnCount(0);

                // add specified columns to table
                for (int i = 1; i <= columnCount; i++ ) {
                    tm.addColumn(rsmd.getColumnName(i));
                }   

                // clear existing rows
                tm.setRowCount(0);

                // add rows to table
                while (rs.next()) {
                    String[] a = new String[columnCount];
                    for(int i = 0; i < columnCount; i++) {
                        a[i] = rs.getString(i+1);
                    }
                    tm.addRow(a);
                }
                tm.fireTableDataChanged();

                rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormLista.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tbCategorias.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
        TableColumnAdjuster tca = new TableColumnAdjuster(tbCategorias);
        tca.adjustColumns();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbCategorias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DQSG(G) - Listagem Crua");
        setMaximumSize(new java.awt.Dimension(1400, 1050));
        setMinimumSize(new java.awt.Dimension(900, 675));
        setPreferredSize(new java.awt.Dimension(930, 700));

        jScrollPane1.setAlignmentX(1.0F);
        jScrollPane1.setAlignmentY(1.0F);

        tbCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCategorias.setAlignmentX(1.0F);
        tbCategorias.setAlignmentY(1.0F);
        tbCategorias.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tbCategorias.setColumnSelectionAllowed(true);
        tbCategorias.setMaximumSize(new java.awt.Dimension(5000, 5000));
        jScrollPane1.setViewportView(tbCategorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormLista().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCategorias;
    // End of variables declaration//GEN-END:variables
}
