package dqgg;

import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 * Formulario para lista e edição dos Aloquiros
 * @author AntonioSousa
 */

public class FormAloquiro extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    JFileChooser fcImagem;   // Janela (dialog) para selecao de arquivos de imagem    
    BD dqggDB;
    Aloquiro aloqAtual = new Aloquiro();   // Registro atualmente exibido
    HashMap filtroConsulta = new HashMap();        // Filtro de consulta atual
    ArrayList<Aloquiro> aloqsConsulta = new ArrayList<Aloquiro>();        // registros retornado pela consulta corrente
    int indiceConsulta = 0;
    
    enum Modo {INCLUSAO, ALTERACAO, CONSULTA, GRAVACAO, ESPERA};
    Modo modoForm = Modo.ALTERACAO;
    
    /**
     * Creates new form FormBD
     */
    public FormAloquiro() {
        initComponents();        
        
        File directory = new File(DQGG.pathImg + "img/");            
        fcImagem = new JFileChooser(directory);
        
        //Acrescenta um filtro para listar somente imagens  
        this.fcImagem.addChoosableFileFilter(new ImageFilter());
        this.fcImagem.setAcceptAllFileFilterUsed(false);

        //Adiciona icones customizados para os tipos de arquivos
        this.fcImagem.setFileView(new ImageFileView());

        //Adiciona o painel de visualizacao
        this.fcImagem.setAccessory(new ImagePreview(this.fcImagem));
                
        aloqAtual = aloqAtual.buscaPrimeiro();
                
        ArrayList<Quirema> quiremas = this.aloqAtual.getQuirema().buscaTodos();
        
        for (Quirema q: quiremas)
            this.comboQuirema.addItem(q.getDescricao());
        
        this.atualizaFormulario(aloqAtual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAbreviatura = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtImgAloquiro = new javax.swing.JTextField();
        btImgAloquiro = new javax.swing.JButton();
        PanelImgAloquiro = new javax.swing.JPanel();
        ImgAloquiro = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboQuirema = new javax.swing.JComboBox();
        PanelNavigator = new javax.swing.JPanel();
        btPrimeiro = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        btUltimo = new javax.swing.JButton();
        btIncluir = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();

        setTitle("DQSG(G) - Aloquiros");
        setMaximumSize(new java.awt.Dimension(860, 590));
        setMinimumSize(new java.awt.Dimension(860, 590));
        setPreferredSize(new java.awt.Dimension(860, 650));

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(812, 65));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Abreviatura:");

        txtAbreviatura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAbreviatura.setAlignmentX(0.0F);
        txtAbreviatura.setPreferredSize(new java.awt.Dimension(244, 23));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAbreviatura, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 142, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAbreviatura, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        jPanel3.setAlignmentX(0.0F);
        jPanel3.setPreferredSize(new java.awt.Dimension(812, 117));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescricao.setRows(5);
        txtDescricao.setAlignmentX(0.0F);
        jScrollPane1.setViewportView(txtDescricao);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 140, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setAlignmentX(0.0F);
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 250));

        jPanel6.setMinimumSize(new java.awt.Dimension(180, 10));
        jPanel6.setPreferredSize(new java.awt.Dimension(600, 5));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Imagem:");
        jPanel6.add(jLabel4);

        txtImgAloquiro.setEditable(false);
        txtImgAloquiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtImgAloquiro.setAlignmentX(0.0F);
        txtImgAloquiro.setAlignmentY(0.0F);
        txtImgAloquiro.setMaximumSize(new java.awt.Dimension(2147, 2147));
        txtImgAloquiro.setPreferredSize(new java.awt.Dimension(490, 30));
        jPanel6.add(txtImgAloquiro);

        btImgAloquiro.setText("Imagem...");
        btImgAloquiro.setAlignmentX(1.0F);
        btImgAloquiro.setMaximumSize(new java.awt.Dimension(95, 30));
        btImgAloquiro.setMinimumSize(new java.awt.Dimension(95, 30));
        btImgAloquiro.setPreferredSize(new java.awt.Dimension(95, 30));
        btImgAloquiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImgAloquiroActionPerformed(evt);
            }
        });
        jPanel6.add(btImgAloquiro);

        PanelImgAloquiro.setBackground(new java.awt.Color(255, 255, 255));
        PanelImgAloquiro.setPreferredSize(new java.awt.Dimension(698, 147));

        ImgAloquiro.setBackground(new java.awt.Color(255, 255, 255));
        ImgAloquiro.setForeground(new java.awt.Color(255, 255, 255));
        ImgAloquiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgAloquiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ImgAloquiro.setMaximumSize(new java.awt.Dimension(244, 180));
        ImgAloquiro.setMinimumSize(new java.awt.Dimension(244, 180));

        javax.swing.GroupLayout PanelImgAloquiroLayout = new javax.swing.GroupLayout(PanelImgAloquiro);
        PanelImgAloquiro.setLayout(PanelImgAloquiroLayout);
        PanelImgAloquiroLayout.setHorizontalGroup(
            PanelImgAloquiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgAloquiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelImgAloquiroLayout.setVerticalGroup(
            PanelImgAloquiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgAloquiro, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelImgAloquiro, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 139, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelImgAloquiro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);

        jPanel5.setAlignmentX(0.0F);
        jPanel5.setPreferredSize(new java.awt.Dimension(812, 69));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Sematosema:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(comboQuirema, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 140, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboQuirema, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5);

        PanelNavigator.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelNavigator.setAlignmentX(0.0F);
        PanelNavigator.setPreferredSize(new java.awt.Dimension(812, 51));

        btPrimeiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPrimeiro.setText("|<");
        btPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrimeiroActionPerformed(evt);
            }
        });

        btAnterior.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAnterior.setText("<");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btProximo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btProximo.setText(">");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        btUltimo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btUltimo.setText(">|");
        btUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUltimoActionPerformed(evt);
            }
        });

        btIncluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btConfirmar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btConsultar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNavigatorLayout = new javax.swing.GroupLayout(PanelNavigator);
        PanelNavigator.setLayout(PanelNavigatorLayout);
        PanelNavigatorLayout.setHorizontalGroup(
            PanelNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavigatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPrimeiro, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProximo, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelNavigatorLayout.setVerticalGroup(
            PanelNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNavigatorLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(PanelNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btPrimeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAnterior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btProximo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btUltimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        jPanel1.add(PanelNavigator);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void entraModoConsulta()
    {        
        this.modoForm = Modo.CONSULTA;
        this.limpaCampos();
        // Altera a cor dos campos
        this.txtAbreviatura.setBackground(DQGG.corConsulta);
        this.txtDescricao.setBackground(DQGG.corConsulta);
        this.txtImgAloquiro.setBackground(DQGG.corDesabilitado);        
    }
    
    private void entraModoAlteracao()
    {
        this.modoForm = Modo.ALTERACAO;
        // Altera a cor dos campos         
        this.txtAbreviatura.setBackground(DQGG.corAlteracao);
        this.txtDescricao.setBackground(DQGG.corAlteracao);
        this.txtImgAloquiro.setBackground(DQGG.corAlteracao);        
    }
    
    private void entraModoInclusao()
    {
        this.modoForm = Modo.INCLUSAO;
        this.limpaCampos();
        // Altera a cor dos campos 
        this.txtAbreviatura.setBackground(DQGG.corInsercao);
        this.txtDescricao.setBackground(DQGG.corInsercao);
        this.txtImgAloquiro.setBackground(DQGG.corInsercao);        
    }
    
    private void atualizaFormulario(Aloquiro aloq)
    {
        // Atualiza os valores dos campos de texto
        this.txtAbreviatura.setText(aloq.getAbreviatura());
        this.txtDescricao.setText(aloq.getDescricao());
        this.txtImgAloquiro.setText(aloq.getImagem());
         // Redesenha as imagens        
        this.ImgAloquiro.setIcon(Utils.getImagem(aloq.getImagem()));
                
        this.comboQuirema.setSelectedItem(this.aloqAtual.getQuirema().getDescricao()); 
    }
    
    private void limpaCampos()
    {
        // Atualiza os valores dos campos de texto
        this.txtAbreviatura.setText("");
        this.txtDescricao.setText("");
        this.txtImgAloquiro.setText("");
        // Redesenha as imagens
        this.ImgAloquiro.setIcon(null);
        this.comboQuirema.setSelectedIndex(-1);
    }
    
    private void btImgAloquiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImgAloquiroActionPerformed
        //Clique do botão "Selecionar Imagem..." (campo Representação)
        if ((evt.getSource() == this.btImgAloquiro)&&(this.modoForm != Modo.CONSULTA)) {
            int returnVal = this.fcImagem.showOpenDialog(this);
 
            if (returnVal == JFileChooser.APPROVE_OPTION) {                
                File file = this.fcImagem.getSelectedFile();                
                String caminhoRelativo = Utils.getRelativePath(file, new File(DQGG.pathApp));                
                this.txtImgAloquiro.setText(caminhoRelativo);
                this.ImgAloquiro.setIcon(new javax.swing.ImageIcon(file.getPath()));
            }    
        }        
    }//GEN-LAST:event_btImgAloquiroActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        HashMap camposAlterados = new HashMap();        
                
        if (this.modoForm == Modo.INCLUSAO)
        {
            // Valida os campos             
            if (this.txtAbreviatura.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Campo Movimentos obrigatório!","ERRO",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (this.txtDescricao.getText().isEmpty())            
            {                
                JOptionPane.showMessageDialog(this,"Campo Descrição obrigatório!","ERRO",JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Insere o aloquiro no banco
            Aloquiro aloq = new Aloquiro(0, this.txtDescricao.getText(), this.txtAbreviatura.getText(), this.txtImgAloquiro.getText(), this.aloqAtual.getQuirema().getId());            
            aloq.insereBD();
            this.entraModoAlteracao();
        
            //Navega para o registro incluido
            Aloquiro r = this.aloqAtual.buscaUltimo();            
            this.atualizaFormulario(aloqAtual=r);
            
        } else if (this.modoForm == Modo.CONSULTA) {
            if (this.aloqsConsulta.isEmpty())
            {   
                // Verifica os campos que foram preenchidos
                if (!this.txtAbreviatura.getText().isEmpty())            
                    this.filtroConsulta.put("ABREVIATURA", this.txtAbreviatura.getText());            

                if (!this.txtDescricao.getText().isEmpty())                                        
                    this.filtroConsulta.put("DESCRICAO", this.txtDescricao.getText());
                
                if (!this.txtDescricao.getText().isEmpty())                                        
                    this.filtroConsulta.put("IMG_ALOQUIRO", this.txtImgAloquiro.getText());

                if (this.filtroConsulta.isEmpty()) 
                {
                   JOptionPane.showMessageDialog(this,"Não há parâmetros para busca!","ALERTA",JOptionPane.INFORMATION_MESSAGE);               
                }
                else
                {
                   this.aloqsConsulta = this.aloqAtual.consultaBD(this.filtroConsulta);    
                   this.aloqAtual = this.aloqsConsulta.get(0);    // pega o primeiro registro da consulta
                   indiceConsulta = 0;
                   this.atualizaFormulario(aloqAtual);
                }
            }
            
        } else if (this.modoForm == Modo.ALTERACAO) {
            // Valida os campos             
            if (this.txtAbreviatura.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Campo Abreviatura obrigatório!.","ERRO",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (this.txtDescricao.getText().isEmpty())            
            {                
                JOptionPane.showMessageDialog(this,"Campo Descrição obrigatório!.","ERRO",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Verifica os campos que foram alterados           
           
            if (!this.txtAbreviatura.getText().equals(this.aloqAtual.getAbreviatura()))            
                camposAlterados.put("ABREVIATURA", this.txtAbreviatura.getText());            
            
            if (!this.txtDescricao.getText().equals(this.aloqAtual.getDescricao()))                                        
                camposAlterados.put("DESCRICAO", this.txtDescricao.getText());
            
            if (!this.txtImgAloquiro.getText().equals(this.aloqAtual.getImagem()))                            
                camposAlterados.put("IMG_ALOQUIRO", this.txtImgAloquiro.getText());            
                        
            if (camposAlterados.isEmpty()) 
            {
               JOptionPane.showMessageDialog(this,"Não há alterações a serem salvas!.","ALERTA",JOptionPane.INFORMATION_MESSAGE);               
            }
            else
            {
               if (this.aloqAtual.atualizaBD(camposAlterados))                    
                   JOptionPane.showMessageDialog(this,"Dados alterados com sucesso!");
               else
                   JOptionPane.showMessageDialog(this,"Erro durante a atualização de dados!","ERRO",JOptionPane.ERROR_MESSAGE);
            }                
        }
        
        
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrimeiroActionPerformed
        if (this.modoForm == Modo.ALTERACAO)    // vai para o primeiro registro da tabela
        {
            Aloquiro r = this.aloqAtual.buscaPrimeiro();
            if (r != null)
                this.atualizaFormulario(aloqAtual=r);
        }
        else if ((this.modoForm == Modo.CONSULTA)&&(!this.aloqsConsulta.isEmpty()))    // vai para o primeiro registro da consulta
        {
            this.aloqAtual = this.aloqsConsulta.get(0);
            this.atualizaFormulario(aloqAtual);
        }
    }//GEN-LAST:event_btPrimeiroActionPerformed

    private void btUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUltimoActionPerformed
        if (this.modoForm == Modo.ALTERACAO)
        {
            Aloquiro r = this.aloqAtual.buscaUltimo();
            if (r != null)
                this.atualizaFormulario(aloqAtual=r);
        }
        else if ((this.modoForm == Modo.CONSULTA)&&(!this.aloqsConsulta.isEmpty()))    // vai para o ultimo registro da consulta
        {
            indiceConsulta = this.aloqsConsulta.size()-1;
            this.aloqAtual = this.aloqsConsulta.get(indiceConsulta);
            this.atualizaFormulario(aloqAtual);
        }
    }//GEN-LAST:event_btUltimoActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        if (this.modoForm == Modo.ALTERACAO)
        {
            Aloquiro r = this.aloqAtual.buscaAnterior(this.aloqAtual);
            if (r != null)
                this.atualizaFormulario(aloqAtual=r);
        }
        else if ((this.modoForm == Modo.CONSULTA)&&(!this.aloqsConsulta.isEmpty()))    // vai para o registro anterior da consulta
        {
            if (indiceConsulta > 0) 
                indiceConsulta--;
            this.aloqAtual = this.aloqsConsulta.get(indiceConsulta);
            this.atualizaFormulario(aloqAtual);
        }
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        if (this.modoForm == Modo.ALTERACAO)
        {
            Aloquiro r = this.aloqAtual.buscaProximo(this.aloqAtual);
            if (r != null)
                this.atualizaFormulario(aloqAtual=r);
        }
        else if ((this.modoForm == Modo.CONSULTA)&&(!this.aloqsConsulta.isEmpty()))    // vai para o registro anterior da consulta
        {
            if (indiceConsulta < (this.aloqsConsulta.size()-1)) 
                indiceConsulta++;
            this.aloqAtual = this.aloqsConsulta.get(indiceConsulta);
            this.atualizaFormulario(aloqAtual);
        }
    }//GEN-LAST:event_btProximoActionPerformed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        if (this.modoForm == Modo.CONSULTA)   //Limpa os registros e o filtro de consulta
        {              
                 this.aloqsConsulta.clear();           
                 this.filtroConsulta.clear();    
        }        
        this.entraModoInclusao();        
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
           if (this.modoForm == Modo.CONSULTA)   //Limpa os registros e o filtro de consulta
           {              
                    this.aloqsConsulta.clear();           
                    this.filtroConsulta.clear();    
           }
            this.entraModoAlteracao();
            if (this.aloqAtual == null)  // consulta que não retornou nenhum registro
            {
                this.aloqAtual = this.aloqAtual.buscaPrimeiro();                
            }
            this.atualizaFormulario(aloqAtual);       
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        if (this.modoForm == Modo.CONSULTA)
        {
            //if (!this.aloqsConsulta.isEmpty())   // retira o filtro de consulta
                this.aloqsConsulta.clear();
                this.filtroConsulta.clear();
            
        }
        this.entraModoConsulta();        
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (this.modoForm != Modo.ALTERACAO)
            return;
        
        int opcao = JOptionPane.showConfirmDialog(this,
                                              "Confirmar exclusão do registro?",
                                              "CONFIRMAÇÃO",
                                              JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) 
        {
           // Pega o registro anterior ao atual
           Aloquiro aloq = this.aloqAtual.buscaAnterior(aloqAtual);
           if (aloq == null)
               aloq = this.aloqAtual.buscaProximo(aloqAtual);
                      
           if (this.aloqAtual.exclui()){
               JOptionPane.showMessageDialog(this,"Dados alterados com sucesso!");               
               this.atualizaFormulario(this.aloqAtual=aloq);
           } else {
               JOptionPane.showMessageDialog(this,"Erro durante a esclusão de dados!","ERRO",JOptionPane.ERROR_MESSAGE);
           }
        }
        
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAloquiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAloquiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAloquiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAloquiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAloquiro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgAloquiro;
    private javax.swing.JPanel PanelImgAloquiro;
    private javax.swing.JPanel PanelNavigator;
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btImgAloquiro;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btPrimeiro;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btUltimo;
    private javax.swing.JComboBox comboQuirema;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAbreviatura;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtImgAloquiro;
    // End of variables declaration//GEN-END:variables
}
